export const site = { brand: 'ZAAD', domain: 'zeroapplesaday.com', colors: { blue: '#0B5FFF', cyan: '#22C1FF', lightBlue: '#60D8FF', navy: '#0A2A52', dark: '#06192F' } };
export const features = ['Lead Management','Centralized Inbox','Pipeline Management','SMS Automation','Email Automation','AI Follow-Up','Missed Call Recovery','Appointment Scheduling','Lead Qualification','Call Tracking','Review Requests','Database Reactivation','Reporting','Team Management','Task Management','Campaign Attribution'];
export const stages = [['01','ATTRACT','Google Ads · Meta Ads · Landing Pages · Organic'],['02','CAPTURE','Forms · Calls · Website Chat · Lead Capture'],['03','QUALIFY','Lead scoring · Qualification · Service fit · Intent'],['04','FOLLOW UP','SMS · Email · AI conversations · Automations'],['05','BOOK','Calendar · Scheduling · Confirmations · Reminders'],['06','RETAIN & REACTIVATE','Reviews · Reactivation · Nurturing · Referrals']];
export const faqs = [['How does ZAAD work?','ZAAD connects patient acquisition, lead capture, qualification, follow-up, booking, and reactivation into one measurable workflow.'],['Does ZAAD replace my staff?','No. ZAAD removes repetitive follow-up work and gives your team clearer tasks, context, and visibility.'],['Does ZAAD run Google Ads and Meta Ads?','Yes. Patient acquisition can include Google Ads, Meta Ads, landing pages, conversion tracking, and ongoing optimization.'],['Can ZAAD handle missed calls?','Yes. A missed call can trigger an immediate response workflow that starts a conversation and routes the opportunity toward booking.'],['Can ZAAD automate SMS?','Yes. SMS can be used for lead response, follow-up, reminders, reactivation, and review workflows.'],['Can ZAAD book appointments?','Yes. The booking layer is integration-ready for calendars and scheduling platforms.'],['Can ZAAD reactivate old leads?','Yes. Dormant inquiries, no-shows, and other eligible contacts can be placed into reactivation campaigns.'],['Is ZAAD HIPAA compliant?','Compliance depends on the configured technology stack, vendors, contracts, workflows, and data handled. ZAAD does not make an unsupported blanket HIPAA-compliance claim.'],['What information should we avoid putting into marketing systems?','Avoid putting sensitive health information into marketing systems unless the system and configuration have been explicitly assessed and approved for that use.'],['How much does ZAAD cost?','Plans are configurable by practice needs. Book a strategy call for a tailored growth plan.']];
export const pricing = [
 { name:'ZAAD FOUNDATION', description:'The operating layer for practices starting to build a repeatable patient-flow system.', features:['CRM','Lead management','SMS + email','Appointment booking','Reporting'] },
 { name:'ZAAD GROWTH', description:'For practices ready to turn acquisition into a measurable pipeline.', features:['Everything in Foundation','Google Ads','Meta Ads','Landing pages','Conversion tracking','Missed call recovery'] },
 { name:'ZAAD PERFORMANCE', description:'For teams that want acquisition, automation, and optimization working together.', features:['Everything in Growth','AI follow-up','Reactivation','Review automation','Call tracking','Advanced reporting'] },
 { name:'ZAAD SCALE', description:'For multi-provider or multi-location growth programs.', features:['Everything in Performance','Team workflows','Advanced attribution','Custom integrations','Dedicated support'] }
];
