import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts, type ErrorComponentProps } from '@tanstack/react-router';
import { useEffect, type ReactNode } from 'react';
import appCss from '../styles.css?url';
import { reportLovableError } from '../lib/lovable-error-reporting';
function NotFoundComponent(){return <div style={{padding:60,fontFamily:'Montserrat,sans-serif'}}><h1>404</h1><p>Page not found.</p><Link to="/">Back to ZAAD</Link></div>}
function ErrorComponent({error,reset}:ErrorComponentProps){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:'tanstack_root_error_component'})},[error]);return <div style={{padding:60,fontFamily:'Montserrat,sans-serif'}}><h1>This page didn't load</h1><p>Try again or return home.</p><button onClick={()=>{router.invalidate();reset()}}>Try again</button> <a href="/">Home</a></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:'utf-8'},{name:'viewport',content:'width=device-width, initial-scale=1'},{title:'ZAAD | Patient Acquisition + CRM for Healthcare Practices'},{name:'description',content:'ZAAD connects patient acquisition, CRM, automation, and follow-up to help healthcare practices turn opportunities into booked appointments.'},{name:'author',content:'Zero Apples A Day'},{property:'og:title',content:'ZAAD | Bring Patients In'},{property:'og:description',content:'Patient acquisition, CRM, automation, and follow-up built for healthcare practices.'},{property:'og:type',content:'website'},{property:'og:url',content:'https://zeroapplesaday.com'},{name:'twitter:card',content:'summary_large_image'}],links:[{rel:'stylesheet',href:appCss},{rel:'icon',href:'/favicon.ico',type:'image/x-icon'}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}
