import { ArrowRight, Bot, Check, PhoneCall, RefreshCw, Star, Target } from 'lucide-react';
import './zaad-extended.css';

const sections = [
  { id: 'acquisition', kicker: '01 / PATIENT ACQUISITION', title: 'Bring the right patients in.', body: 'Paid acquisition, local visibility, landing pages, offers, and conversion paths work together to turn attention into real patient inquiries.', icon: Target, items: ['Paid patient acquisition', 'Local SEO & search visibility', 'Conversion-focused landing pages', 'Offers & campaign strategy'] },
  { id: 'nurture', kicker: '02 / AI NURTURE + BOOKING', title: 'Every lead gets a next step.', body: 'The moment a patient reaches out, the system responds, qualifies, follows up, schedules, and confirms the appointment.', icon: Bot, items: ['Instant lead response', 'Patient qualification', 'Automated follow-up', 'Appointment scheduling & confirmation'] },
  { id: 'missed', kicker: '03 / MISSED CALL RECOVERY', title: 'A missed call does not have to become a lost patient.', body: 'When your team cannot answer, ZAAD starts the follow-up conversation automatically so the patient gets another opportunity to connect and book.', icon: PhoneCall, items: ['Missed call detection', 'Automated patient outreach', 'Conversation recovery', 'Appointment confirmation'] },
  { id: 'reputation', kicker: '04 / 5-STAR REPUTATION', title: 'Turn great experiences into public trust.', body: 'Our reputation funnel gives happy patients a simple path to leave feedback and helps your practice build a stronger review presence over time.', icon: Star, items: ['Review-request journeys', 'Patient feedback flow', 'Timing & follow-up', 'Reputation visibility'] },
  { id: 'reactivation', kicker: '05 / DATABASE REACTIVATION', title: 'Your old patient database is an asset.', body: 'We take the data you already have, segment it, create relevant offers, and send targeted messaging campaigns that restart conversations with past patients.', icon: RefreshCw, items: ['Database segmentation', 'Targeted discount offers', 'Messaging campaigns', 'Reactivation appointment flow'] },
];

export default function ZaadExtendedSections() {
  return <>
    <section className="zx-acquisition" id="acquisition"><div className="zx-container"><div className="zx-intro"><span className="zx-kicker">THE ENGINE STARTS HERE</span><h2>Every part of ZAAD has <em>a job.</em></h2><p>We do not just hand you leads. We build the connected journey that moves a patient from first touch to appointment — and keeps working after they leave.</p></div><div className="zx-stack">{sections.map((s, i) => { const Icon = s.icon; return <article className={`zx-service ${i % 2 ? 'reverse' : ''}`} id={s.id} key={s.id}><div className="zx-service-visual"><div className="zx-orb"/><div className="zx-ui-window"><div className="zx-ui-top"><span>ZAAD / {s.kicker.split(' / ')[1]}</span><i>LIVE</i></div><div className="zx-ui-core"><Icon size={30}/><b>{i === 0 ? 'PATIENT DEMAND' : i === 1 ? 'LEAD → BOOKED' : i === 2 ? 'MISSED → RECOVERED' : i === 3 ? 'EXPERIENCE → TRUST' : 'OLD DATA → ACTIVE'}</b></div><div className="zx-ui-lines"><span/><span/><span/></div></div></div><div className="zx-service-copy"><span className="zx-kicker">{s.kicker}</span><h3>{s.title}</h3><p>{s.body}</p><div className="zx-checks">{s.items.map(item => <span key={item}><Check size={13}/>{item}</span>)}</div><a href="/book">See how this works <ArrowRight size={15}/></a></div></article>})}</div></div></section>

    <section className="zx-journey" id="journey"><div className="zx-container"><div className="zx-intro centered"><span className="zx-kicker">THE COMPLETE PATIENT JOURNEY</span><h2>From first click to <em>patient for life.</em></h2><p>Everything connects. Nothing gets stranded between marketing, front desk, phone calls, follow-up, and the next visit.</p></div><div className="zx-timeline">{[['ATTRACT','Create demand','Ads, SEO, offers'],['CAPTURE','Catch every inquiry','Forms, calls, chat'],['NURTURE','Keep the conversation alive','AI follow-up'],['BOOK','Put it on the calendar','Scheduling + confirmation'],['GROW','Keep the relationship','Reviews + reactivation']].map(([a,b,c],i)=><div className="zx-step" key={a}><span>0{i+1}</span><b>{a}</b><h4>{b}</h4><p>{c}</p></div>)}</div></div></section>

    <section className="zx-healthcare" id="healthcare"><div className="zx-container"><div className="zx-intro centered"><span className="zx-kicker">BUILT FOR HEALTHCARE</span><h2>One growth system. <em>Different practices.</em></h2><p>The patient journey changes by specialty. The underlying growth engine does not.</p></div><div className="zx-practices">{['Psychiatry','Dentistry','Chiropractic','Med Spas','Primary Care','Specialty Clinics','Mental Health','Aesthetic Practices'].map((name,i)=><div className="zx-practice" key={name}><span>0{i+1}</span><strong>{name}</strong><ArrowRight size={15}/></div>)}</div></div></section>

    <section className="zx-footer-cta"><div className="zx-footer-glow"/><div className="zx-container zx-cta-inner"><span className="zx-kicker">READY TO BUILD THE ENGINE?</span><h2>Bring more patients in.<br/><em>Then stop losing them.</em></h2><p>Build the acquisition, nurture, booking, recovery, reputation, and reactivation system your practice should have had all along.</p><a href="/book">Book a Strategy Call <ArrowRight size={16}/></a></div></section>

    <footer className="zx-footer"><div className="zx-container"><div className="zx-footer-main"><div className="zx-footer-brand"><div className="zx-logo">ZAAD<span>.</span></div><p>Patient growth infrastructure for modern healthcare practices.</p><a href="/book" className="zx-footer-call">Talk to ZAAD <ArrowRight size={14}/></a></div><div className="zx-footer-links"><div><b>Platform</b><a href="#acquisition">Patient Acquisition</a><a href="#nurture">AI Nurture + Booking</a><a href="#missed">Missed Call Recovery</a><a href="#reputation">Reputation</a><a href="#reactivation">Reactivation</a></div><div><b>Product</b><a href="#app">Doctor App</a><a href="#app">UniBox</a><a href="#journey">How It Works</a><a href="#results">Growth Estimator</a></div><div><b>Company</b><a href="#healthcare">Who We Help</a><a href="/pricing">Pricing</a><a href="/book">Book a Call</a></div></div></div><div className="zx-footer-bottom"><span>© 2026 ZAAD. All rights reserved.</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><span>APPLE KEEPS THE DOCTOR AWAY. ZAAD BRINGS PATIENTS IN.</span></div></div></footer>
  </>;
}
