import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, BarChart3, Bot, CalendarCheck, Check, ChevronDown, CircleCheck, Clock3, Globe2, Headphones, LayoutDashboard, Menu, MessageSquare, PhoneCall, Play, Plus, RefreshCw, ShieldCheck, Sparkles, Star, Target, Users, X, Zap } from 'lucide-react';
import { features, faqs, pricing, stages } from '../lib/site-data';

const Button = ({ children, href = '/book', secondary = false }: { children: React.ReactNode; href?: string; secondary?: boolean }) => <a href={href} className={`zaad-btn ${secondary ? 'zaad-btn-secondary' : ''}`}>{children}<ArrowRight size={17}/></a>;

function Logo({ dark = false }: { dark?: boolean }) { return <a href="/" className="zaad-logo" aria-label="ZAAD home"><span className="logo-mark"><span className="logo-door"/><span className="logo-person p1"/><span className="logo-person p2"/></span><span className={dark ? 'logo-word light' : 'logo-word'}>ZAAD</span></a>; }

function Navbar() {
 const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{ const on=()=>setScrolled(window.scrollY>24); window.addEventListener('scroll',on); on(); return()=>window.removeEventListener('scroll',on)},[]);
 const links=[['Solutions','#system'],['Who We Help','#industries'],['How It Works','#how-it-works'],['Results','#results'],['Pricing','/pricing'],['About','/about']];
 return <header className={`zaad-nav ${scrolled?'scrolled':''}`}><div className="container nav-inner"><Logo/><nav className="desktop-nav">{links.map(([l,h])=><a key={l} href={h}>{l}{['Solutions','Who We Help'].includes(l)&&<ChevronDown size={13}/>}</a>)}</nav><div className="nav-actions"><a className="nav-secondary" href="#how-it-works">See How ZAAD Works</a><Button>Book a Strategy Call</Button></div><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-drawer">{links.map(([l,h])=><a key={l} href={h} onClick={()=>setOpen(false)}>{l}<ArrowUpRight size={15}/></a>)}<a href="/psychiatrists" onClick={()=>setOpen(false)}>Psychiatrists<ArrowUpRight size={15}/></a><a className="drawer-cta" href="/book">Book a Strategy Call <ArrowRight size={16}/></a></div>}</header>
}

function FlowVisual(){ return <div className="flow-visual"><div className="flow-grid"/><div className="flow-orbit orbit-a"/><div className="flow-orbit orbit-b"/><div className="apple-core"><span className="apple-leaf"/><div className="apple-body"><div className="apple-door"/><span/><span/></div></div><div className="flow-node node-a"><span>AD</span><small>Demand</small></div><div className="flow-node node-b"><span>LEAD</span><small>Captured</small></div><div className="flow-node node-c"><span>CRM</span><small>Organized</small></div><div className="flow-node node-d"><span>AI</span><small>Follow-up</small></div><div className="flow-node node-e"><span>BOOKED</span><small>Appointment</small></div><div className="flow-line line-1"/><div className="flow-line line-2"/><div className="flow-line line-3"/><div className="flow-line line-4"/><div className="flow-badge"><CircleCheck size={15}/> Patient flow active</div></div> }

function Dashboard(){ const cols=[['NEW LEAD',['Maya R.','Jordan K.']],['CONTACTED',['Daniel P.','Ava M.']],['QUALIFIED',['Olivia S.','Noah B.']],['BOOKED',['Emma T.','Liam W.']]]; return <div className="dashboard"><div className="dash-top"><div><span className="dash-eyebrow">ZAAD CRM</span><h3>Patient Pipeline</h3></div><button className="mini-btn"><Plus size={14}/> Add lead</button></div><div className="metric-row"><div><span>New leads</span><strong>184</strong><em>+18.4%</em></div><div><span>Booked</span><strong>72</strong><em>+12.1%</em></div><div><span>Conversion</span><strong>39.1%</strong><em>+6.8%</em></div><div><span>Show-up</span><strong>91%</strong><em>+4.2%</em></div></div><div className="pipeline">{cols.map(([title,names],i)=><div className="pipeline-col" key={title}><div className="pipeline-head"><span>{title}</span><b>{(names as string[]).length}</b></div>{(names as string[]).map((n,j)=><div className="lead-card" key={n}><div className="avatar">{n[0]}</div><div><strong>{n}</strong><small>{i===0?'Google Ads':i===1?'Meta Ads':'Website'} · {i+2*10+9} score</small></div><MoreDots/></div>)}</div>)}</div><div className="dash-footer"><span><span className="pulse"/> All systems healthy</span><span>Updated just now</span></div></div> }
const MoreDots=()=> <span className="dots">•••</span>;

export default function ZaadHome(){ const [activeStage,setActiveStage]=useState(0); const [faq,setFaq]=useState<number|null>(0); return <div className="zaad-site"><Navbar/>
<section className="hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> PATIENT ACQUISITION FOR HEALTHCARE PRACTICES</div><h1>An Apple a Day Keeps the Doctor Away.</h1><h2>ZAAD Does the Opposite — <span>It Brings Patients In.</span></h2><p>Performance marketing, patient acquisition, CRM automation, and intelligent follow-up — connected into one system that turns opportunities into booked appointments.</p><div className="hero-actions"><Button>Book a Strategy Call</Button><Button secondary href="#how-it-works"><Play size={16}/> See How ZAAD Works</Button></div><div className="hero-checks">{['Attract the right patients','Respond instantly','Follow up automatically','Book more appointments'].map(x=><span key={x}><Check size={15}/>{x}</span>)}</div></div><FlowVisual/></div></section>
<section className="trust"><div className="container"><p>Built for practices that care about growth — not vanity metrics.</p><div className="trust-row">{['PRACTICE 01','PRACTICE 02','PRACTICE 03','PRACTICE 04','PRACTICE 05'].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="section problem"><div className="container"><div className="section-head center"><span className="kicker">THE REAL LEAK</span><h2>Most Practices Don't Have a Lead Problem.<br/><span>They Have a Patient Flow Problem.</span></h2><p>A lead that waits is a lead that drifts. ZAAD connects every handoff between first click and scheduled appointment.</p></div><div className="problem-grid"><div className="problem-card bad"><div className="card-tag">WITHOUT ZAAD</div><div className="flow-stack">{['Ad clicks','Lead comes in','Nobody responds','Lead goes cold','Appointment never happens'].map((x,i)=><div key={x} className="stack-item"><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span>{i<4&&<ArrowRight size={15}/>}</div>)}</div><div className="loss-line"><X size={16}/> Opportunity lost</div></div><div className="problem-card good"><div className="card-tag">WITH ZAAD</div><div className="flow-stack">{['Ad','Lead','Instant response','Qualification','Follow-up','Booking','Reminder','Patient shows up'].map((x,i)=><div key={x} className="stack-item"><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span>{i<7&&<ArrowRight size={15}/>}</div>)}</div><div className="win-line"><Check size={16}/> Patient flow connected</div></div></div></div></section>
<section id="system" className="section system-section"><div className="container"><div className="section-head center light"><span className="kicker">THE ZAAD SYSTEM</span><h2>One System.<br/><span>Every Step From Click to Patient.</span></h2><p>Six connected layers. One clear view of what happens next.</p></div><div className="stage-tabs">{stages.map((s,i)=><button key={s[0]} className={activeStage===i?'active':''} onClick={()=>setActiveStage(i)}><small>{s[0]}</small><strong>{s[1]}</strong></button>)}</div><div className="stage-detail"><div className="stage-number">{stages[activeStage][0]}</div><div><span className="kicker">{stages[activeStage][1]}</span><h3>{stages[activeStage][2].split(' · ')[0]}</h3><p>{stages[activeStage][2].split(' · ').slice(1).join(' · ')}</p></div><div className="stage-icon"><Zap size={28}/></div></div></div></section>
<section className="section crm-section"><div className="container"><div className="two-col"><div className="section-head"><span className="kicker">MEET ZAAD CRM</span><h2>Every lead. Every conversation. <span>Every follow-up.</span> One place.</h2><p>Give your team a live pipeline instead of a pile of tabs, missed calls, and forgotten callbacks.</p><ul className="check-list">{['See where every opportunity stands','Know what needs attention next','Measure booked appointments — not just clicks','Keep acquisition and follow-up connected'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><Button href="/crm">Explore ZAAD CRM</Button></div><Dashboard/></div></div></section>
<section className="section feature-section"><div className="container"><div className="section-head center"><span className="kicker">THE OPERATING LAYER</span><h2>Everything Your Team Needs <span>After the Click.</span></h2></div><div className="feature-grid">{features.map((x,i)=><div className="feature-card" key={x}><div className="feature-icon">{[Bot,MessageSquare,Target,PhoneCall,CalendarCheck,RefreshCw][i%6] && (()=>{const I=[Bot,MessageSquare,Target,PhoneCall,CalendarCheck,RefreshCw][i%6];return <I size={19/>})()}</div><h3>{x}</h3><span>Connected to patient flow</span></div>)}</div></div></section>
<section id="acquisition" className="section acquisition"><div className="container"><div className="two-col reverse"><div className="acq-visual"><div className="channel-card"><span>GOOGLE ADS</span><strong>High-intent demand</strong><div className="bars"><i/><i/><i/><i/><i/></div><small>Search → landing page → booked</small></div><div className="channel-card offset"><span>META ADS</span><strong>Qualified audiences</strong><div className="audience"><Users size={18}/><span>Reach + nurture</span></div></div><div className="connector"><ArrowRight size={18}/><span>ZAAD</span><ArrowRight size={18}/></div></div><div className="section-head"><span className="kicker">PATIENT ACQUISITION</span><h2>Get More of the Patients <span>You Actually Want.</span></h2><p>ZAAD doesn't optimize simply for cheap leads. We build campaigns around qualified opportunities and booked appointments.</p><div className="mini-list">{['Campaign strategy','Offer positioning','Creative + landing pages','Conversion tracking','A/B testing + optimization'].map(x=><span key={x}><Check size={15}/>{x}</span>)}</div><Button href="/book">Build My Patient Acquisition System</Button></div></div></div></section>
<section id="ai-follow-up" className="section ai-section"><div className="container"><div className="two-col"><div className="section-head"><span className="kicker">AI-ASSISTED FOLLOW-UP</span><h2>Your Leads Shouldn't Have to <span>Wait for Someone to Call Back.</span></h2><p>Respond fast, answer common questions, qualify opportunities, route conversations, and help move the right people toward scheduling.</p><div className="ai-points">{['Respond instantly','Qualify leads','Handle common objections','Trigger staff tasks','Help schedule appointments'].map(x=><span key={x}><CircleCheck size={16}/>{x}</span>)}</div><small className="guardrail">ZAAD does not diagnose, prescribe, or provide medical advice.</small></div><div className="chat-card"><div className="chat-top"><span><span className="live-dot"/> ZAAD Assistant</span><small>Conversation #1842</small></div><div className="chat-body"><div className="bubble patient">Hi, I'm interested in scheduling an appointment.</div><div className="bubble zaad">Absolutely. I can help with that. Are you looking for an initial consultation?</div><div className="bubble patient">Yes. What times are available?</div><div className="typing">ZAAD is preparing options <i/><i/><i/></div><div className="booking-chip"><CalendarCheck size={16}/><span><strong>Appointment booked</strong><small>Thursday · 11:00 AM</small></span><Check size={16}/></div></div></div></div></div></section>
<section className="section dark-flow"><div className="container"><div className="two-col"><div><span className="kicker">MISSED CALL RECOVERY</span><h2>A Missed Call Shouldn't Become <span>a Lost Patient.</span></h2><p>Turn unanswered calls into conversations while the intent is still warm.</p><div className="missed-flow">{['MISSED CALL','INSTANT SMS','CONVERSATION','QUALIFICATION','BOOKING'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span>{i<4&&<ArrowRight size={16}/>}</div>)}</div></div><div className="sms-card"><div className="phone-top"><PhoneCall size={15}/> Missed call recovered</div><div className="sms"><span>NOW</span><p>Hi! We just missed your call from <strong>[Practice Name]</strong>. How can we help?</p></div><div className="sms-reply">I'd like to schedule a consultation.</div><div className="sms-footer"><CircleCheck size={15}/> Lead captured · follow-up started</div></div></div></div></section>
<section className="section reactivate"><div className="container"><div className="section-head center"><span className="kicker">REACTIVATION</span><h2>Your Old Leads Are <span>Still an Asset.</span></h2><p>Re-engage eligible dormant opportunities, unbooked inquiries, no-shows, and past contacts with thoughtful campaigns.</p></div><div className="reactivation-visual"><div className="big-number">1,248<small>old contacts</small></div><ArrowRight className="react-arrow"/><div className="react-step"><RefreshCw size={23}/><strong>Reactivation campaign</strong><span>Personalized outreach</span></div><ArrowRight className="react-arrow"/><div className="react-result"><CalendarCheck size={23}/><strong>Appointments</strong><span>New opportunities</span></div></div></div></section>
<section id="reviews" className="section reviews"><div className="container"><div className="section-head center"><span className="kicker">REPUTATION</span><h2>Turn Great Patient Experiences <span>Into Social Proof.</span></h2><p>Automate review requests and route internal feedback without manufacturing testimonials.</p></div><div className="review-grid">{['PATIENT REVIEW PLACEHOLDER','PATIENT REVIEW PLACEHOLDER','PATIENT REVIEW PLACEHOLDER'].map((x,i)=><div className="review-card" key={i}><div className="stars">★★★★★</div><p>{x}</p><span>Replace with a verified testimonial</span></div>)}</div></div></section>
<section id="how-it-works" className="section how"><div className="container"><div className="section-head center"><span className="kicker">HOW IT WORKS</span><h2>Seven Steps From <span>Search to Show.</span></h2></div><div className="timeline">{[['01','ATTRACT','Bring qualified traffic.'],['02','CAPTURE','Capture every opportunity.'],['03','RESPOND','Respond immediately.'],['04','QUALIFY','Identify serious opportunities.'],['05','FOLLOW UP','Keep conversations moving.'],['06','BOOK','Turn interest into appointments.'],['07','SHOW','Improve confirmation and attendance.']].map(([n,t,d])=><div className="timeline-item" key={n}><div className="time-num">{n}</div><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><div className="timeline-end">That's ZAAD.</div></div></section>
<section id="results" className="section results"><div className="container"><div className="section-head center"><span className="kicker">RESULTS</span><h2>Measure What <span>Actually Matters.</span></h2><p>No vanity scoreboard. Track the numbers that connect marketing activity to patient opportunities.</p></div><div className="result-metrics">{['Leads','Qualified Leads','Booked Appointments','Cost Per Lead','Cost Per Appointment','Show-Up Rate','Revenue Opportunities'].map((x,i)=><div key={x}><span>{x}</span><strong>{['—','—','—','—','—','—','—'][i]}</strong><small>Configured when real data is added</small></div>)}</div><div className="case-placeholder"><div><span className="kicker">CASE STUDIES</span><h3>Real practice stories belong here.</h3><p>Numbers stay data-driven. Add verified case studies and screenshots without changing the page components.</p></div><Button href="/results">Explore Results</Button></div></div></section>
<section id="industries" className="section industries"><div className="container"><div className="section-head"><span className="kicker">WHO WE HELP</span><h2>Built for Healthcare Practices.<br/><span>Psychiatry Is Where We Start.</span></h2></div><div className="industry-grid">{['Psychiatrists','Mental Health Practices','Chiropractors','Dental Practices','Physical Therapy','Med Spas','Specialty Clinics'].map((x,i)=><a href={i===0?'/psychiatrists':'#industries'} className={i===0?'featured':''} key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong><ArrowUpRight size={18}/></a>)}</div></div></section>
<section className="section faq"><div className="container faq-grid"><div className="section-head"><span className="kicker">FAQ</span><h2>Questions before <span>you start?</span></h2><p>Clear answers. No compliance shortcuts.</p><Button href="/book">Talk to ZAAD</Button></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-item ${faq===i?'open':''}`} key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span>{faq===i?<X size={17}/>:<Plus size={17}/>}</button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
<section className="final-cta"><div className="container"><div className="cta-glow"/><span className="kicker">READY TO FIX THE FLOW?</span><h2>Your Next Patient Is Already Looking.<br/><span>Make Sure They Find You.</span></h2><p>ZAAD connects patient acquisition, CRM, automation, and follow-up into one system built to turn opportunities into appointments.</p><div className="hero-actions"><Button>Book a Strategy Call</Button><Button secondary href="/crm">Explore ZAAD CRM</Button></div></div></section>
<footer><div className="container"><div className="footer-main"><div><Logo dark/><p>An Apple a Day Keeps the Doctor Away.<br/><strong>ZAAD Does the Opposite — It Brings Patients In.</strong></p></div><div className="footer-col"><h4>Solutions</h4><a href="#acquisition">Patient Acquisition</a><a href="/crm">ZAAD CRM</a><a href="#ai-follow-up">AI Follow-Up</a><a href="/book">Appointment Booking</a><a href="#reviews">Reviews</a></div><div className="footer-col"><h4>Who We Help</h4><a href="/psychiatrists">Psychiatrists</a><a href="#industries">Mental Health</a><a href="#industries">Chiropractic</a><a href="#industries">Dental</a><a href="#industries">Physical Therapy</a></div><div className="footer-col"><h4>Company</h4><a href="/about">About</a><a href="/results">Results</a><a href="/pricing">Pricing</a><a href="/book">Book a Call</a><a href="/contact">Contact</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Zero Apples A Day. All rights reserved.</span><span><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/cookies">Cookies</a></span></div></div></footer>
</div> }
