import { useState } from 'react';
import { ArrowRight, Bot, CalendarCheck, Database, MessageCircle, PhoneMissed, ShieldCheck, Smartphone, Star, Target, Zap } from 'lucide-react';

const modules = [
 {id:'acquisition',icon:Target,label:'Bring Patients In',title:'Build a predictable flow of new patient leads.',copy:'Paid acquisition, local search, landing pages and offers put your practice in front of people ready to take the next step.',items:['Paid & local acquisition','Conversion-focused landing pages','Offers that create action']},
 {id:'booking',icon:Bot,label:'Nurture + Book',title:'Every lead gets a response — and a path to the calendar.',copy:'Our automated agent responds, follows up, qualifies the opportunity and books the appointment.',items:['Instant lead response','Automated follow-up','Appointment booking + confirmation']},
 {id:'missed',icon:PhoneMissed,label:'Recover Missed Calls',title:'Turn missed calls back into conversations.',copy:'When the clinic cannot answer, the system reaches back out automatically and helps the patient continue toward an appointment.',items:['Missed-call detection','Automated outreach','Appointment confirmation']},
 {id:'reputation',icon:Star,label:'5-Star Reputation',title:'Turn great patient experiences into stronger reputation.',copy:'A dedicated reputation funnel asks for feedback at the right moment and makes it easy for happy patients to leave a review.',items:['Feedback funnel','Review requests','Reputation visibility']},
 {id:'reactivation',icon:Database,label:'Reactivate Your Database',title:'Your old patient list can create new appointments.',copy:'We segment the clinic’s existing database and send targeted offers through messaging to bring past patients back.',items:['Database segmentation','Discount campaigns','Automated messaging']},
 {id:'app',icon:Smartphone,label:'Manage It All',title:'One app. One inbox. One view of patient growth.',copy:'The doctor can see leads, conversations, appointments and progress from the mobile app, while UniBox brings different lead channels into one place.',items:['Doctor mobile app','UniBox conversations','Leads + pipeline + appointments']},
];

export default function ZaadSystemPage(){
 const [active,setActive]=useState('acquisition'); const item=modules.find(x=>x.id===active)!; const Icon=item.icon;
 return <>
 <section id="system" className="zs-system"><div className="zs-container"><div className="zs-intro"><div><span className="zs-eyebrow">THE ZAAD SYSTEM</span><h2>Not another tool.<br/><em>A system that moves patients.</em></h2></div><p>From the first lead to the booked appointment — and from missed calls to old databases — ZAAD connects the parts of patient growth that are usually handled separately.</p></div>
 <div className="zs-product"><div className="zs-tabs">{modules.map(m=>{const I=m.icon;return <button key={m.id} className={active===m.id?'active':''} onClick={()=>setActive(m.id)}><I size={17}/><span>{m.label}</span></button>})}</div><div className="zs-detail"><div className="zs-detail-copy"><span className="zs-eyebrow">{item.label}</span><h3>{item.title}</h3><p>{item.copy}</p><div className="zs-list">{item.items.map((x,i)=><div key={i}><ShieldCheck size={16}/><span>{x}</span></div>)}</div><a href="/book" className="zs-link">See how ZAAD fits your practice <ArrowRight size={15}/></a></div><div className="zs-visual"><div className="zs-visual-top"><span><Icon size={15}/> ZAAD SYSTEM</span><b>ACTIVE</b></div><div className="zs-flow"><div className="zs-node">{active==='acquisition'?'AD / SEARCH':active==='booking'?'NEW LEAD':active==='missed'?'MISSED CALL':active==='reputation'?'PATIENT':active==='reactivation'?'OLD DATABASE':'ALL CHANNELS'}</div><div className="zs-line"/><div className="zs-agent"><Zap size={18}/><strong>{active==='app'?'UNIBOX':active==='reputation'?'REPUTATION':active==='reactivation'?'CAMPAIGN':'ZAAD AGENT'}</strong><small>{active==='acquisition'?'CAPTURE':active==='booking'?'NURTURE + BOOK':active==='missed'?'REACH OUT':active==='reputation'?'REVIEW FUNNEL':active==='reactivation'?'MESSAGE + OFFER':'ONE PLACE'}</small></div><div className="zs-line"/><div className="zs-node success">{active==='reputation'?'5-STAR REVIEW':active==='reactivation'?'REACTIVATED':active==='app'?'MANAGE + TRACK':'APPOINTMENT'}</div></div><div className="zs-metrics"><span><b>{active==='acquisition'?'LEADS':active==='booking'?'FOLLOW-UPS':active==='missed'?'RECOVERED':active==='reputation'?'REVIEWS':active==='reactivation'?'REACTIVATIONS':'CONVERSATIONS'}</b><strong>LIVE</strong></span><span><b>STATUS</b><strong>CONNECTED</strong></span></div></div></div></div></div></section>
 <section className="zs-proof"><div className="zs-container"><div className="zs-proof-grid"><div><Target/><strong>Acquire</strong><span>Bring new demand in</span></div><div><MessageCircle/><strong>Nurture</strong><span>Keep leads moving</span></div><div><CalendarCheck/><strong>Book</strong><span>Fill the calendar</span></div><div><Star/><strong>Grow</strong><span>Reputation + reactivation</span></div></div></div></section>
 <section id="how-it-works" className="zs-journey"><div className="zs-container"><div className="zs-center"><span className="zs-eyebrow">ONE CONNECTED FLOW</span><h2>From <em>“I’m interested”</em><br/>to <em>“See you then.”</em></h2></div><div className="zs-journey-line">{['Lead comes in','ZAAD responds','Agent follows up','Appointment booked','Clinic gets the patient'].map((x,i)=><div key={x}><i>{i+1}</i><strong>{x}</strong>{i<4&&<span/>}</div>)}</div></div></section>
 <section className="zs-stack"><div className="zs-container"><div className="zs-stack-copy"><span className="zs-eyebrow">THE ADVANTAGE</span><h2>What happens <em>around</em> the appointment matters too.</h2><p>ZAAD does not stop when a lead books. Missed calls are recovered, happy patients are guided toward reviews, and old databases are given a reason to come back.</p><a href="/book" className="zs-cta">Build your patient growth system <ArrowRight size={16}/></a></div><div className="zs-stack-cards"><div><PhoneMissed/><b>Missed Call Recovery</b><span>Automated outreach after the call you could not answer.</span></div><div><Star/><b>5-Star Reputation</b><span>A simple funnel for feedback and reviews.</span></div><div><Database/><b>Database Reactivation</b><span>Targeted offers sent to patients you already know.</span></div></div></div></section>
 <section id="results" className="zs-control"><div className="zs-container"><div className="zs-control-copy"><span className="zs-eyebrow">THE DOCTOR'S VIEW</span><h2>Everything your team needs.<br/><em>Nothing scattered.</em></h2><p>The mobile app gives the doctor a clear view of leads and progress. UniBox pulls conversations from different routes into one place.</p><div className="zs-app-points"><span><Smartphone/>Mobile app</span><span><MessageCircle/>UniBox</span><span><CalendarCheck/>Appointments</span></div></div><div className="zs-phone"><div className="zs-phone-notch"/><small>ZAAD</small><h4>Good morning, Doctor</h4><div className="zs-stat"><span>Patient pipeline</span><b>24 active</b><i>↗</i></div><div className="zs-inbox"><div><MessageCircle/><b>UniBox</b><small>12 conversations</small></div><div><CalendarCheck/><b>Appointments</b><small>7 today</small></div><div><Target/><b>New leads</b><small>9 this week</small></div></div></div></div></section>
 <section className="zs-final"><div className="zs-container"><span className="zs-eyebrow">BUILT AROUND YOUR PRACTICE</span><h2>More patients in.<br/><em>Less chasing.</em></h2><p>One connected patient-growth system for practices that want their marketing, follow-up and front desk working together.</p><a href="/book" className="zs-cta light">Book a Strategy Call <ArrowRight size={16}/></a></div></section>
 <footer className="zs-footer"><div className="zs-container"><div><strong>ZAAD</strong><span>Apple keeps the doctor away. ZAAD brings patients in.</span></div><nav><a href="#system">Solutions</a><a href="#how-it-works">How It Works</a><a href="#results">Platform</a><a href="/book">Book a Call</a></nav><small>© {new Date().getFullYear()} ZAAD. All rights reserved.</small></div></footer>
 </>;
}
