import { useState } from 'react';
import { ArrowRight, CalendarCheck, Check, ChevronDown, CircleCheck, Menu, MessageSquare, PhoneCall, Play, RefreshCw, Sparkles, Users, X, Zap } from 'lucide-react';

const steps=[
  ['01','ATTRACT THE RIGHT PATIENTS','Google Ads, Meta Ads, landing pages, and offers built around the patients a practice actually wants.'],
  ['02','CAPTURE EVERY INQUIRY','Forms, calls, chat, and campaigns feed into one organized patient pipeline.'],
  ['03','RESPOND BEFORE THEY DRIFT','Fast SMS and email follow-up keeps the conversation moving while intent is high.'],
  ['04','FOLLOW UP & QUALIFY','Automations help answer common questions, qualify opportunities, and surface what staff needs to do next.'],
  ['05','BOOK THE APPOINTMENT','Scheduling, confirmations, and reminders turn conversations into calendar events.'],
  ['06','RETAIN, REACTIVATE & SCALE','Reviews, dormant-lead reactivation, reporting, and optimization keep the system compounding.']
];
const features=['Lead Management','Centralized Inbox','Pipeline Management','SMS Automation','Email Automation','AI-Assisted Follow-Up','Missed Call Recovery','Appointment Scheduling','Lead Qualification','Call Tracking','Review Requests','Database Reactivation'];
const testimonials=[
  ['“The biggest difference is visibility. We finally know where every inquiry is and what should happen next.”','Practice owner','Mental Health Practice'],
  ['“We stopped treating every lead like a spreadsheet row. The follow-up feels immediate and intentional.”','Practice director','Specialty Clinic'],
  ['“ZAAD gives our team one operating picture from first click to booked appointment.”','Growth lead','Healthcare Group']
];

const Btn=({children,href='/book',secondary=false}:{children:React.ReactNode;href?:string;secondary?:boolean})=><a href={href} className={`zaad-btn ${secondary?'zaad-btn-secondary':''}`}>{children}<ArrowRight size={15}/></a>;
const Logo=()=> <a href="/" className="zaad-logo"><span className="logo-mark"><span className="logo-door"/><span className="logo-person p1"/><span className="logo-person p2"/></span><span className="logo-word">ZAAD</span></a>;

function Nav(){const [open,setOpen]=useState(false);return <header className="zaad-nav"><div className="container nav-inner"><Logo/><nav><a href="#system">Solutions <ChevronDown size={12}/></a><a href="#industries">Who We Help <ChevronDown size={12}/></a><a href="#how-it-works">How It Works</a><a href="#results">Results</a><a href="/pricing">Pricing</a><a href="/about">About</a></nav><div className="nav-actions"><a className="nav-secondary" href="#how-it-works">See How ZAAD Works</a><Btn>Book a Strategy Call</Btn></div><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-drawer"><a href="#system" onClick={()=>setOpen(false)}>Solutions</a><a href="#industries" onClick={()=>setOpen(false)}>Who We Help</a><a href="#how-it-works" onClick={()=>setOpen(false)}>How It Works</a><a href="/psychiatrists">Psychiatrists</a><a href="/pricing">Pricing</a><a href="/book">Book a Strategy Call</a></div>}</header>}

function HeroVisual(){return <div className="hero-art"><div className="art-glow"/><div className="art-grid"/><div className="art-title">PATIENT<br/><span>FLOW</span></div><div className="art-center"><Sparkles size={28}/><strong>ZAAD</strong><small>Growth System</small></div>{[['AD','Demand'],['LEAD','Captured'],['CRM','Organized'],['AI','Follow-up'],['BOOK','Appointment']].map(([a,b],i)=><div className={`art-node art-${i}`} key={a}><b>{a}</b><small>{b}</small></div>)}<div className="art-line l1"/><div className="art-line l2"/><div className="art-line l3"/><div className="art-line l4"/><div className="art-badge"><CircleCheck size={13}/> Patient flow active</div></div>}

function SocialProof(){return <section className="social-proof"><div className="container"><p>BUILT FOR PRACTICES THAT CARE ABOUT GROWTH — NOT VANITY METRICS.</p><div className="proof-grid">{testimonials.map(([quote,who,where])=><article className="quote-card" key={quote}><div className="quote-top"><span>★★★★★</span><span className="quote-dot"/></div><blockquote>{quote}</blockquote><div className="quote-person"><div className="avatar">{who[0]}</div><div><strong>{who}</strong><small>{where}</small></div></div></article>)}</div></div></section>}

function DataSection(){return <section className="dark-section data-section"><div className="container"><div className="section-head light center"><span className="kicker cyan">REAL DATA. REAL CONVERSATIONS.</span><h2>Stop Losing Patients <span>Between the Click and the Calendar.</span></h2><p>ZAAD connects acquisition, response, follow-up, qualification, and booking so your team can see what is happening instead of guessing.</p></div><div className="data-grid"><div className="data-card large"><span className="data-label">LIVE PATIENT PIPELINE</span><div className="mini-pipeline">{['NEW','CONTACTED','QUALIFIED','BOOKED'].map((x,i)=><div key={x}><b>{x}</b>{['Maya R.','Daniel P.','Olivia S.','Emma T.'][i]}<small>{['Google Ads','SMS follow-up','Website','Calendar'][i]}</small></div>)}</div></div><div className="data-card chat-demo"><span className="data-label">AI-ASSISTED FOLLOW-UP</span><div className="chat-bubble patient">Hi, I’m interested in scheduling an appointment.</div><div className="chat-bubble bot">Absolutely. I can help with that. Are you looking for an initial consultation?</div><div className="chat-bubble patient">Yes. What times are available?</div><div className="booking"><CalendarCheck size={15}/><span><b>Appointment booked</b><small>Thursday · 11:00 AM</small></span><Check size={15}/></div></div></div></div></section>}

function SystemSection(){return <section id="system" className="section system"><div className="container"><div className="section-head center"><span className="kicker">THE ZAAD SYSTEM</span><h2>More Patients. <span>Fewer Leaks.</span></h2><p>Every part of your patient journey works together instead of living in separate tools and inboxes.</p></div><div className="feature-grid">{features.map((x,i)=><article className="feature-card" key={x}><div className="feature-num">{String(i+1).padStart(2,'0')}</div><div className="feature-icon"><Zap size={17}/></div><h3>{x}</h3><p>Connected to the patient-flow system.</p></article>)}</div></div></section>}

function PatientFlow(){const [active,setActive]=useState(0);return <section id="how-it-works" className="blue-section"><div className="container"><div className="section-head light center"><span className="kicker cyan">PATIENT FLOW</span><h2>From First Click <span>to Patient.</span></h2><p>One connected journey, with a clear next step at every stage.</p></div><div className="flow-layout"><div className="flow-nav">{steps.map((s,i)=><button key={s[0]} className={active===i?'active':''} onClick={()=>setActive(i)}><b>{s[0]}</b><span>{s[1]}</span><ArrowRight size={15}/></button>)}</div><div className="flow-detail"><span className="step-count">{steps[active][0]}</span><div className="step-icon"><Sparkles size={22}/></div><h3>{steps[active][1]}</h3><p>{steps[active][2]}</p><div className="flow-pills"><span><Check size={12}/> Connected</span><span><Zap size={12}/> Automated</span><span><CircleCheck size={12}/> Measurable</span></div></div></div></div></section>}

function WhySection(){return <section className="dark-section why"><div className="container two-col"><div><span className="kicker cyan">WHY THIS APPROACH WORKS</span><h2>Growth Is Not Just <span>Getting More Leads.</span></h2><p>Healthcare practices lose opportunities in the handoffs: slow response, missed calls, inconsistent follow-up, unclear ownership, and no visibility.</p><div className="why-list">{['One patient pipeline instead of scattered tools','Fast response while intent is still high','Clear ownership for every opportunity','Acquisition measured against booked outcomes'].map(x=><div key={x}><CircleCheck size={16}/><span>{x}</span></div>)}</div><Btn>Build My Patient Acquisition System</Btn></div><div className="why-art"><div className="orbit-card"><div className="orbit-core"><strong>ZAAD</strong><small>CONNECTED GROWTH</small></div><span className="orbit-pill p-a">Acquisition</span><span className="orbit-pill p-b">CRM</span><span className="orbit-pill p-c">Follow-up</span><span className="orbit-pill p-d">Booking</span></div></div></div></section>}

function AboutSection(){return <section className="section about"><div className="container two-col"><div className="about-card"><div className="about-logo">ZAAD</div><div className="about-stat"><strong>01</strong><span>connected growth system</span></div><div className="about-lines"><i/><i/><i/></div></div><div className="section-head"><span className="kicker">ABOUT ZAAD</span><h2>Built Around One Simple Idea: <span>Patient Flow Matters.</span></h2><p>ZAAD is designed to help healthcare practices connect marketing, lead management, automation, follow-up, and booking into one operating system.</p><p>We focus on the work that happens after someone clicks, calls, or fills out a form — because that is where many good opportunities disappear.</p><Btn href="/about">Learn More About ZAAD</Btn></div></div></section>}

function Results(){return <section id="results" className="section results"><div className="container"><div className="section-head center"><span className="kicker">REAL RESULTS. REAL PRACTICES.</span><h2>Track the Numbers <span>That Matter.</span></h2><p>Replace vanity metrics with a clearer view of qualified opportunities, appointments, show-ups, and growth.</p></div><div className="metrics">{[['01','Qualified Leads'],['02','Booked Appointments'],['03','Cost Per Appointment'],['04','Show-Up Rate']].map(([n,t])=><div key={t}><span>{n}</span><strong>—</strong><b>{t}</b><small>Connect your real practice data here</small></div>)}</div><div className="review-row">{testimonials.map(([q,w,wh])=><article key={w}><span>“</span><p>{q}</p><strong>{w}</strong><small>{wh}</small></article>)}</div></div></section>}

function Industries(){return <section id="industries" className="section industries"><div className="container"><div className="section-head"><span className="kicker">WHO WE HELP</span><h2>Built for Healthcare Practices.<br/><span>Psychiatry Is Where We Start.</span></h2></div><div className="industry-grid">{['Psychiatrists','Mental Health Practices','Chiropractors','Dental Practices','Physical Therapy','Med Spas','Specialty Clinics'].map((x,i)=><a href={i===0?'/psychiatrists':'#industries'} key={x}><span>0{i+1}</span><strong>{x}</strong><ArrowRight size={16}/></a>)}</div></div></section>}

function FinalCta(){return <section className="final-cta"><div className="cta-people"><div/><div/><div/><div/></div><div className="container cta-inner"><span className="kicker cyan">READY TO GROW?</span><h2>Ready to Get More Patients <span>Without More Chaos?</span></h2><p>Let's build a patient acquisition system that gives your practice a clearer path from click to appointment.</p><div><Btn>Book a Strategy Call</Btn><Btn href="/crm" secondary>Explore ZAAD CRM</Btn></div></div></section>}

function Footer(){return <footer><div className="container footer-grid"><div><Logo/><p>Patient acquisition, CRM, automation, and follow-up for healthcare practices.</p></div><div><b>Solutions</b><a href="/crm">ZAAD CRM</a><a href="/psychiatrists">Psychiatrists</a><a href="/pricing">Pricing</a></div><div><b>Company</b><a href="/about">About</a><a href="/results">Results</a><a href="/contact">Contact</a></div><div><b>Start Here</b><a href="/book">Book a Strategy Call</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div><div className="footer-bottom"><div className="container"><span>© {new Date().getFullYear()} ZAAD. All rights reserved.</span><span>Patient flow, connected.</span></div></div></footer>}

export default function ZaadHome(){return <div className="zaad-site"><Nav/><section className="hero reference-hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><i/> PATIENT ACQUISITION FOR HEALTHCARE PRACTICES</div><h1>What More Patients <span>Need?</span></h1><h2>ZAAD Connects the Journey <span>From Click to Appointment.</span></h2><p>Performance marketing, CRM automation, intelligent follow-up, and booking — connected into one patient-flow system built for healthcare practices.</p><div className="hero-actions"><Btn>Book a Strategy Call</Btn><Btn secondary href="#how-it-works"><Play size={14}/> See How ZAAD Works</Btn></div><div className="hero-checks">{['Attract the right patients','Respond instantly','Follow up automatically','Book more appointments'].map(x=><span key={x}><Check size={13}/>{x}</span>)}</div></div><HeroVisual/></div></section><SocialProof/><DataSection/><SystemSection/><PatientFlow/><WhySection/><AboutSection/><Results/><Industries/><FinalCta/><Footer/></div>}
