import { useState } from 'react';
import { ArrowRight, Bot, CalendarCheck, Database, MessageCircle, PhoneMissed, ShieldCheck, Smartphone, Star, Target, Zap } from 'lucide-react';

const modules = [
 {id:'acquisition',icon:Target,label:'Bring Patients In',title:'Build a predictable flow of new patient leads.',copy:'Paid acquisition, local search, landing pages and offers put your practice in front of people ready to take the next step.',items:['Paid & local acquisition','Conversion-focused landing pages','Offers that create action']},
 {id:'booking',icon:Bot,label:'Nurture + Book',title:'Every lead gets a response — and a path to the calendar.',copy:'Our automated agent responds, follows up, qualifies the opportunity and books the appointment.',items:['Instant lead response','Automated follow-up','Appointment booking + confirmation']},
 {id:'missed',icon:PhoneMissed,label:'Recover Missed Calls',title:'Turn missed calls back into conversations.',copy:'When the clinic cannot answer, the system reaches back out automatically and helps the patient continue toward an appointment.',items:['Missed-call detection','Automated outreach','Appointment confirmation']},
 {id:'reputation',icon:Star,label:'5-Star Reputation',title:'Turn great patient experiences into stronger reputation.',copy:'A dedicated reputation funnel asks for feedback at the right moment and makes it easy for happy patients to leave a review.',items:['Feedback funnel','Review requests','Reputation visibility']},
 {id:'reactivation',icon:Database,label:'Reactivate Your Database',title:'Your old patient list can create new appointments.',copy:'We segment the clinic’s existing database and send targeted offers through messaging to bring past patients back.',items:['Database segmentation','Discount campaigns','Automated messaging']},
 {id:'app',icon:Smartphone,label:'Manage It All',title:'One app. One inbox. One view of patient growth.',copy:'The doctor can see leads, conversations, appointments and progress from the mobile app, while UniBox brings different lead channels into one place.',items:['Doctor mobile app','UniBox conversations','Leads + pipeline + appointments']},
];

export default function ZaadSystemCore(){
 const [active,setActive]=useState('acquisition'); const item=modules.find(x=>x.id===active)!; const Icon=item.icon;
 return <section id="system" className="zs-system"><div className="zs-container"><div className="zs-intro"><div><span className="zs-eyebrow">THE ZAAD SYSTEM</span><h2>Not another tool.<br/><em>A system that moves patients.</em></h2></div><p>From the first lead to the booked appointment — and from missed calls to old databases — ZAAD connects the parts of patient growth that are usually handled separately.</p></div><div className="zs-product"><div className="zs-tabs">{modules.map(m=>{const I=m.icon;return <button key={m.id} className={active===m.id?'active':''} onClick={()=>setActive(m.id)}><I size={17}/><span>{m.label}</span></button>})}</div><div className="zs-detail"><div className="zs-detail-copy"><span className="zs-eyebrow">{item.label}</span><h3>{item.title}</h3><p>{item.copy}</p><div className="zs-list">{item.items.map((x,i)=><div key={i}><ShieldCheck size={16}/><span>{x}</span></div>)}</div><a href="/book" className="zs-link">See how ZAAD fits your practice <ArrowRight size={15}/></a></div><div className="zs-visual"><div className="zs-visual-top"><span><Icon size={15}/> ZAAD SYSTEM</span><b>ACTIVE</b></div><div className="zs-flow"><div className="zs-node">{active==='acquisition'?'AD / SEARCH':active==='booking'?'NEW LEAD':active==='missed'?'MISSED CALL':active==='reputation'?'PATIENT':active==='reactivation'?'OLD DATABASE':'ALL CHANNELS'}</div><div className="zs-line"/><div className="zs-agent"><Zap size={18}/><strong>{active==='app'?'UNIBOX':active==='reputation'?'REPUTATION':active==='reactivation'?'CAMPAIGN':'ZAAD AGENT'}</strong><small>{active==='acquisition'?'CAPTURE':active==='booking'?'NURTURE + BOOK':active==='missed'?'REACH OUT':active==='reputation'?'REVIEW FUNNEL':active==='reactivation'?'MESSAGE + OFFER':'ONE PLACE'}</small></div><div className="zs-line"/><div className="zs-node success">{active==='reputation'?'5-STAR REVIEW':active==='reactivation'?'REACTIVATED':active==='app'?'MANAGE + TRACK':'APPOINTMENT'}</div></div><div className="zs-metrics"><span><b>{active==='acquisition'?'LEADS':active==='booking'?'FOLLOW-UPS':active==='missed'?'RECOVERED':active==='reputation'?'REVIEWS':active==='reactivation'?'REACTIVATIONS':'CONVERSATIONS'}</b><strong>LIVE</strong></span><span><b>STATUS</b><strong>CONNECTED</strong></span></div></div></div></div></div></section>;
}
