import { BrandHome } from './BrandLogo';
import { useState } from 'react';
import { ArrowRight, CalendarCheck, Check, ChevronDown, Clock3, Mail, MapPin, Phone, ShieldCheck, Sparkles } from 'lucide-react';
import { pricing } from '../lib/site-data';

export function InnerShell({ eyebrow, title, intro, children, cta='Book a Strategy Call' }: { eyebrow:string; title:string; intro:string; children:React.ReactNode; cta?:string }) { return <div className="zaad-inner"><header className="inner-nav"><div className="container nav-inner"><BrandHome /><div className="inner-links"><a href="/">Home</a><a href="/crm">CRM</a><a href="/psychiatrists">Psychiatrists</a><a href="/pricing">Pricing</a><a href="/book">Book a Call</a></div></div></header><main><section className="inner-hero"><div className="container"><span className="kicker">{eyebrow}</span><h1>{title}</h1><p>{intro}</p><a className="zaad-btn" href="/book">{cta}<ArrowRight size={17}/></a></div></section>{children}</main><footer className="inner-footer"><div className="container"><BrandHome /><span>Patient acquisition + CRM + automation.</span><a href="/">Back to zeroapplesaday.com</a></div></footer></div> }

export function CRMPage(){ return <InnerShell eyebrow="ZAAD CRM" title="Every lead. Every conversation. One place." intro="A healthcare growth operating layer for the moments after someone raises their hand."><section className="inner-section"><div className="container"><div className="dashboard large"><div className="dash-top"><div><span className="dash-eyebrow">LIVE PIPELINE</span><h3>Practice Growth Dashboard</h3></div><span className="status-pill"><span/> Connected</span></div><div className="metric-row"><div><span>New Leads</span><strong>184</strong><em>+18.4%</em></div><div><span>Booked</span><strong>72</strong><em>+12.1%</em></div><div><span>Conversion Rate</span><strong>39.1%</strong><em>+6.8%</em></div><div><span>Show-Up Rate</span><strong>91%</strong><em>+4.2%</em></div></div><div className="crm-table">{['NEW LEAD','CONTACTED','QUALIFIED','BOOKED','CONFIRMED','SHOWED','NO SHOW','REACTIVATION'].map((x,i)=><div key={x}><span>{x}</span><b>{[28,41,26,22,18,14,7,28][i]}</b><i style={{width:`${[70,82,60,55,48,40,25,70][i]}%`}}/></div>)}</div></div><div className="inner-copy-grid"><div><span className="kicker">BUILT AROUND THE PIPELINE</span><h2>Know what happened. Know what happens next.</h2></div><div className="feature-list">{['Lead cards with source + score','Last contact + follow-up status','Appointment state from new lead to show','Team assignment + task visibility','Attribution and performance reporting','Reactivation without spreadsheet exports'].map(x=><div key={x}><Check size={17}/>{x}</div>)}</div></div></div></section></InnerShell> }

export function PsychiatryPage(){ return <InnerShell eyebrow="PSYCHIATRY GROWTH SYSTEM" title="Help More Patients Find Your Psychiatry Practice." intro="ZAAD helps psychiatry practices generate qualified inquiries, respond faster, automate follow-up, and turn more opportunities into scheduled consultations." cta="Get My Practice Growth Plan"><section className="inner-section"><div className="container"><div className="psy-grid"><div className="inner-card"><span className="kicker">WHY OPPORTUNITIES LEAK</span><h2>Patients don't always wait.</h2>{['Calls go unanswered',"Leads aren't followed up quickly",'Patients hesitate before booking',"Staff can't consistently follow up","Website visitors don't convert"].map(x=><div className="line-check" key={x}><Check size={16}/>{x}</div>)}</div><div className="inner-card blue"><span className="kicker">HOW ZAAD HELPS</span><h2>Connect the journey.</h2>{['Patient acquisition','Lead capture','AI-assisted follow-up','Appointment booking','Missed call recovery','Reactivation','Reviews','CRM'].map(x=><div className="line-check" key={x}><Check size={16}/>{x}</div>)}</div></div><div className="compliance"><ShieldCheck size={22}/><div><strong>Compliance-aware by design.</strong><p>ZAAD does not make medical-outcome claims, provide medical advice, or require sensitive health information in marketing forms. Any regulated-data workflow should be explicitly configured and assessed for compliant handling.</p></div></div></div></section></InnerShell> }

export function PricingPage(){ const [annual,setAnnual]=useState(false); return <InnerShell eyebrow="PRICING" title="Choose the patient-flow system your practice needs." intro="Start with the operating layer you need today. Expand as acquisition and automation mature."><section className="inner-section"><div className="container"><div className="billing-toggle"><span>Monthly</span><button onClick={()=>setAnnual(!annual)} className={annual?'on':''}><i/></button><span>Annual <b>save more</b></span></div><div className="pricing-grid">{pricing.map((p,i)=><div className={`price-card ${i===2?'featured':''}`} key={p.name}>{i===2&&<span className="popular">MOST POPULAR</span>}<span className="kicker">{p.name}</span><h2>{i===3?'Custom':'$—'}<small>{i===3?'':'/mo'}</small></h2><p>{p.description}</p><a className="zaad-btn" href="/book">Talk to ZAAD <ArrowRight size={16}/></a><ul>{p.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul></div>)}</div><p className="pricing-note">Pricing is intentionally configurable. Final scope, setup, media spend, integrations, and support are confirmed during strategy.</p></div></section></InnerShell> }

export function BookPage(){ const [sent,setSent]=useState(false); if(sent) return <InnerShell eyebrow="CONFIRMED" title="Your Strategy Call Is Confirmed." intro="We'll use the call to find where your patient flow is breaking and identify the highest-leverage next step."><section className="inner-section"><div className="container success-card"><CalendarCheck size={42}/><h2>You're on the calendar.</h2><p>Date · Time · Timezone<br/>Meeting type · Strategy call</p><div className="prep"><strong>Before the call</strong><span>Bring your current lead sources</span><span>Know your approximate monthly lead volume</span><span>Bring your biggest growth constraint</span></div></div></section></InnerShell>;
return <InnerShell eyebrow="BOOK A STRATEGY CALL" title="Let's Find Where Your Patient Flow Is Breaking." intro="Tell us enough to understand the practice. We'll handle the rest." cta="Submit & Continue"><section className="inner-section"><div className="container"><form className="booking-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-step"><span>01</span><div><h3>Practice information</h3><p>Keep it simple. We'll qualify the opportunity on the call.</p></div></div><div className="form-grid">{['Name','Practice name','Email','Phone','Website','City','State','Practice type','Monthly marketing budget','Current lead volume','Current monthly appointments'].map((x)=><label key={x}>{x}<input required={['Name','Practice name','Email'].includes(x)} placeholder={`Enter ${x.toLowerCase()}`}/></label>)}</div><label>Biggest growth challenge<textarea placeholder="What's currently getting in the way?"/></label><div className="form-step"><span>02</span><div><h3>How are you currently getting patients?</h3><p>Select all that apply.</p></div></div><div className="choice-grid">{['Google Ads','Meta Ads','SEO','Referrals','Organic','Other'].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div><div className="form-step"><span>03</span><div><h3>Calendar</h3><p>Embed-ready. Connect your preferred calendar when ready.</p></div></div><div className="calendar-placeholder"><CalendarCheck size={24}/><strong>Calendar integration placeholder</strong><span>Ready for GoHighLevel, Calendly, HubSpot, or a custom booking API.</span></div><button className="zaad-btn" type="submit">Submit & Continue <ArrowRight size={17}/></button></form></div></section></InnerShell> }

export function AboutPage(){ return <InnerShell eyebrow="ABOUT ZAAD" title="We built ZAAD because getting a lead isn't the same as getting a patient." intro="Marketing creates opportunities. ZAAD connects what happens after the opportunity arrives."><section className="inner-section"><div className="container story-grid"><div><h2>The gap is usually not more traffic.</h2><p>Practices lose opportunities because response is slow, follow-up is inconsistent, systems are disconnected, staff is overwhelmed, leads aren't nurtured, or appointments aren't confirmed.</p></div><div className="story-list">{['Attract','Capture','Respond','Qualify','Follow up','Book','Show'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span><ArrowRight size={16}/></div>)}</div></div></section></InnerShell> }

export function ContactPage(){ return <InnerShell eyebrow="CONTACT" title="Have a patient-flow question?" intro="Tell us what you're working on. Or skip the form and book a strategy call."><section className="inner-section"><div className="container contact-grid"><div className="contact-card"><Mail/><strong>Email</strong><span>hello@zeroapplesaday.com</span></div><div className="contact-card"><Phone/><strong>Phone</strong><span>Available during your strategy call</span></div><div className="contact-card"><MapPin/><strong>Service area</strong><span>US healthcare practices</span></div></div><div className="container contact-form-wrap"><form className="booking-form"><div className="form-grid"><label>Name<input placeholder="Your name"/></label><label>Email<input type="email" placeholder="you@practice.com"/></label><label>Practice name<input placeholder="Practice name"/></label><label>Phone<input placeholder="Phone"/></label></div><label>Message<textarea placeholder="How can ZAAD help?"/></label><button className="zaad-btn" type="button">Send message <ArrowRight size={17}/></button></form></div></section></InnerShell> }
